### ISSUE TITLE
Обработка ошибок дочерних компонентов в React

### ISSUE THREAD

**Issue by shoom1337** [Berlevog/yandex.middlefrontend.mario#10]
Пока вообще не понимаю что тут нужно сделать) Помогите тут, или спрошу на следующем созвоне

**Comment by Alkamenos** [comment]
Я думаю это всякие формы, кнопки и инпуты которые мы будем использовать. Но так-как у нас скорее всего будет MUI в нем какая-то базовая обработка уже есть. Я бы конечно сделал в этой задаче клиентскую валидацию на всех формах через https://react-hook-form.com/ + https://github.com/jquense/yup

**Comment by shoom1337** [comment]
Понял, спасибо!

**Comment by shoom1337** [comment]
В этом спринте зесь похоже речь про предохранители https://ru.reactjs.org/docs/error-boundaries.html#introducing-error-boundaries
