### ISSUE TITLE
Реализовать состояния начала и завершения игры

### ISSUE THREAD

**Issue by shoom1337** [Berlevog/yandex.middlefrontend.mario#11]
Пока не ясно что значит "реализовать состяния". Макеты начала и завершения игры я отрисую в фигме, сверстаю их, а дальше? Подскажите тут или спрошу на созвоне

**Comment by Alkamenos** [comment]
У нас в проекте дальше должен быть Redux возможно это связанно с ним

**Comment by sunny-viktoryia** [comment]
на самом деле, нужно чтобы была какая-то кнопочка "начать" - состояние начала игры, потом по нажатию, например, какой-то таймаут, и после этого экран завершения игры - что там будет отображатся. Заглушки, короч.
